server:
  port: ${PORT:8989}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

spring:
  application:
    name: turbine-server

turbine:
  appConfig: front-service
  clusterNameExpression: new String("default")

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/