eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

    instance:
      leaseRenewalIntervalInSeconds: 5

spring:
  application:
    name: back-service

server:
  port: ${PORT:0}
